# Generated by Django 5.0.6 on 2024-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ElencoOrdini", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordine",
            name="cliente",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ordine",
            name="prodotto",
            field=models.CharField(max_length=200),
        ),
    ]
